# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

from .modules.block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C2fMSA,  # 添加多尺度注意力模块
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    MultiScaleAttention,  # 添加多尺度注意力模块
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    TorchVision,
)

from .tasks import (
    BaseModel,
    ClassificationModel,
    DetectionModel,
    SegmentationModel,
    attempt_load_one_weight,
    attempt_load_weights,
    guess_model_scale,
    guess_model_task,
    parse_model,
    torch_safe_load,
    yaml_model_load,
)

__all__ = (
    "attempt_load_one_weight",
    "attempt_load_weights",
    "parse_model",
    "yaml_model_load",
    "guess_model_task",
    "guess_model_scale",
    "torch_safe_load",
    "DetectionModel",
    "SegmentationModel",
    "ClassificationModel",
    "BaseModel",
    # 添加block模块中的类
    "C1", "C2", "C2PSA", "C3", "C3TR", "CIB", "DFL", "ELAN1", "PSA", "SPP", "SPPELAN", "SPPF",
    "A2C2f", "AConv", "ADown", "Attention", "BNContrastiveHead", "Bottleneck", "BottleneckCSP",
    "C2f", "C2fAttn", "C2fCIB", "C2fPSA", "C2fMSA", "C3Ghost", "C3k2", "C3x", "CBFuse", "CBLinear",
    "ContrastiveHead", "GhostBottleneck", "HGBlock", "HGStem", "ImagePoolingAttn", "MultiScaleAttention",
    "Proto", "RepC3", "RepNCSPELAN4", "RepVGGDW", "ResNetLayer", "SCDown", "TorchVision",
)
